### ISSUE TITLE
Kubernetes logdna-agent-v2:stable does not automatically add k8s pod labels

### ISSUE THREAD

**Issue by henkka** [logdna/logdna-agent#99]
Unfortunately with new `image: logdna/logdna-agent-v2:stable` our ingested logs does not seem to be automatically labeled with k8s pod labels. With the earlier `image: logdna/logdna-agent:latest` it does.

Reproduce:
Configure your k8s cluster with `logdna-agent-v2` DaemonSet. Start pod with `kubectl run` with parameter `-l datasetId=nnnnn`. Result: Logs from the pod will be added to LogDNA, but without the pod label (datasetId=nnnnn).

**Comment by CJP10** [comment]
Put this in an update.yaml
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logdna-agent
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: logdna-agent
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: logdna-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logdna-agent
subjects:
  - kind: ServiceAccount
    name: logdna-agent
    namespace: default
```
```
kubectl apply -f update.yaml
kubectl patch ds/logdna-agent -p '{"spec":{"template":{"spec":{"serviceAccountName":"logdna-agent","serviceAccount":"logdna-agent"}}}}'
kubectl patch ds/logdna-agent -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"updated\":\"`date +'%s'`\"}}}}}"
```
